name: "CI"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  e2e_test:
    name: "E2E Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      # https://github.com/actions/setup-node/issues/214#issuecomment-810829250
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
